name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '*'

concurrency: ci-${{ github.ref }}

jobs:
  # First it needs to cache and setup
  prepare:
    name: âš¡ Initialize & Caching
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: ğŸ’¿ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: â³ Setup Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ğŸ­ Install dependencies
        run: yarn install

  # Then we can check the code quality
  quality:
    name: ğŸ” Checking the code
    runs-on: ${{ matrix.os }}
    needs: [prepare]

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: ğŸ’¿ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: â³ Setup Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ğŸ­ Install dependencies
        run: yarn install

      - name: ğŸ•µ Lint the code
        run: yarn lint

      - name: ğŸ’… Run Prettier
        run: yarn prettier

      - name: ğŸ”¬ Run unit tests
        run: yarn test:coverage

      - name: ğŸ“Š Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  # Lets also run some security check
  security:
    if: github.event_name != 'pull_request'
    name: ğŸš¨ Running security check
    runs-on: ${{ matrix.os }}
    needs: [prepare]

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3

      - name: ğŸ’¿ Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: â³ Setup Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ğŸ­ Install dependencies
        run: yarn install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # If quality pass, let's try to build things
  build:
    name: ğŸ” Building the code
    runs-on: ${{ matrix.os }}
    needs: [quality]

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: ğŸ’¿ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: â³ Setup Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ğŸ­ Install dependencies
        run: yarn install

      - name: ğŸ§° Build code
        run: yarn build

      - name: ğŸ“– Build Storybook
        run: yarn build:storybook
