name: Release

on:
  release:
    types: [published]

concurrency: release-${{ github.ref }}

jobs:
  prepare:  
    name: âš¡ Initialize & Caching
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: ğŸ’¿ Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        
      - name: â³ Setup Cache 
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ğŸ­ Install dependencies
        run: yarn install

  release:
    name: ğŸ“¦ Publishing the release
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3

      - name: ğŸ’¿ Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: yarn
      
      - name: ğŸ­ Install packages
        run: yarn install
    
      # - name: ğŸš€ Publish the release
      #   run: yarn publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  pages:
    name: ğŸŒ Publishing the website
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: ğŸ“¥ Check out the code
        uses: actions/checkout@v3

      - name: ğŸ’¿ Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: yarn
      
      - name: ğŸ­ Install packages
        run: yarn install

      - name: ğŸ§° Build code
        run: yarn build

      - name: ğŸ“– Build Storybook
        run: yarn build:storybook

      - name: ğŸš€ Deploy the website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build